#!/usr/bin/env python
# -*- coding:utf-8 -*-
'''
Highly divisible triangular number
Problem 12

The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

Let us list the factors of the first seven triangle numbers:

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
'''
import math


def getFactors(n):
    factors = 0
    for x in xrange(1, int(math.sqrt(n)) + 1):
        if n % x == 0:
            factors += 2
    if (int(math.sqrt(n)))**2 == n:
        factors -= 1
    return factors


def main():
    index = 1
    factors = 0
    while factors < 500:
        n = index * (index + 1) / 2
        factors = getFactors(n)
        index += 1
    print n

if __name__ == '__main__':
    main()
